VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Sheet1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True

Private Sub Begin_Click()
    ComboBox1.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox2.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox3.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox4.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox5.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox6.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox7.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox8.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox9.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox10.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox11.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox12.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox13.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox14.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox15.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox16.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    
    If ComboBox1.Value = "Select Type" Then
    ComboBox1.ListIndex = 0
    End If
    If ComboBox2.Value = "Select Type" Then
    ComboBox2.ListIndex = 0
    End If
    If ComboBox3.Value = "Select Type" Then
    ComboBox3.ListIndex = 0
    End If
    If ComboBox4.Value = "Select Type" Then
    ComboBox4.ListIndex = 0
    End If
    If ComboBox5.Value = "Select Type" Then
    ComboBox5.ListIndex = 0
    End If
    If ComboBox6.Value = "Select Type" Then
    ComboBox6.ListIndex = 0
    End If
    If ComboBox7.Value = "Select Type" Then
    ComboBox7.ListIndex = 0
    End If
    If ComboBox8.Value = "Select Type" Then
    ComboBox8.ListIndex = 0
    End If
    If ComboBox9.Value = "Select Type" Then
    ComboBox9.ListIndex = 0
    End If
    If ComboBox10.Value = "Select Type" Then
    ComboBox10.ListIndex = 0
    End If
    If ComboBox11.Value = "Select Type" Then
    ComboBox11.ListIndex = 0
    End If
    If ComboBox12.Value = "Select Type" Then
    ComboBox12.ListIndex = 0
    End If
    If ComboBox13.Value = "Select Type" Then
    ComboBox13.ListIndex = 0
    End If
    If ComboBox14.Value = "Select Type" Then
    ComboBox14.ListIndex = 0
    End If
    If ComboBox15.Value = "Select Type" Then
    ComboBox15.ListIndex = 0
    End If
    If ComboBox16.Value = "Select Type" Then
    ComboBox16.ListIndex = 0
    End If
    
End Sub


Private Sub Reset_Click()
    ComboBox1.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox2.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox3.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox4.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox5.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox6.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox7.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox8.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox9.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox10.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox11.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox12.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox13.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox14.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox15.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox16.List = Array("Select Type", "Shark 200", "Shark 250", "Shark 270", "Nexus 1500+")
    ComboBox1.ListIndex = 0
    ComboBox2.ListIndex = 0
    ComboBox3.ListIndex = 0
    ComboBox4.ListIndex = 0
    ComboBox5.ListIndex = 0
    ComboBox6.ListIndex = 0
    ComboBox7.ListIndex = 0
    ComboBox8.ListIndex = 0
    ComboBox9.ListIndex = 0
    ComboBox10.ListIndex = 0
    ComboBox11.ListIndex = 0
    ComboBox12.ListIndex = 0
    ComboBox13.ListIndex = 0
    ComboBox14.ListIndex = 0
    ComboBox15.ListIndex = 0
    ComboBox16.ListIndex = 0
End Sub


'----------------------------------------------------------------------------Meter Type Control
Private Sub ComboBox1_Change()
    If ComboBox1.Value <> "Select Type" Then
        ActiveWorkbook.Sheets("Main").Range("D20").Value = ComboBox1.Value
    Else
        ActiveWorkbook.Sheets("Main").Range("D20").Value = ""
    End If
End Sub
Private Sub ComboBox2_Change()
    If ComboBox2.Value <> "Select Type" Then
        ActiveWorkbook.Sheets("Main").Range("D21").Value = ComboBox2.Value
    Else
        ActiveWorkbook.Sheets("Main").Range("D21").Value = ""
    End If
End Sub
Private Sub ComboBox3_Change()
    If ComboBox3.Value <> "Select Type" Then
        ActiveWorkbook.Sheets("Main").Range("D22").Value = ComboBox3.Value
    Else
        ActiveWorkbook.Sheets("Main").Range("D22").Value = ""
    End If
End Sub
Private Sub ComboBox4_Change()
    If ComboBox4.Value <> "Select Type" Then
        ActiveWorkbook.Sheets("Main").Range("D23").Value = ComboBox4.Value
    Else
        ActiveWorkbook.Sheets("Main").Range("D23").Value = ""
    End If
End Sub
Private Sub ComboBox5_Change()
    If ComboBox5.Value <> "Select Type" Then
        ActiveWorkbook.Sheets("Main").Range("D24").Value = ComboBox5.Value
    Else
        ActiveWorkbook.Sheets("Main").Range("D24").Value = ""
    End If
End Sub
Private Sub ComboBox6_Change()
    If ComboBox6.Value <> "Select Type" Then
        ActiveWorkbook.Sheets("Main").Range("D25").Value = ComboBox6.Value
    Else
        ActiveWorkbook.Sheets("Main").Range("D25").Value = ""
    End If
End Sub
Private Sub ComboBox7_Change()
    If ComboBox7.Value <> "Select Type" Then
        ActiveWorkbook.Sheets("Main").Range("D26").Value = ComboBox7.Value
    Else
        ActiveWorkbook.Sheets("Main").Range("D26").Value = ""
    End If
End Sub
Private Sub ComboBox8_Change()
    If ComboBox8.Value <> "Select Type" Then
        ActiveWorkbook.Sheets("Main").Range("D27").Value = ComboBox8.Value
    Else
        ActiveWorkbook.Sheets("Main").Range("D27").Value = ""
    End If
End Sub
Private Sub ComboBox9_Change()
    If ComboBox9.Value <> "Select Type" Then
        ActiveWorkbook.Sheets("Main").Range("D28").Value = ComboBox9.Value
    Else
        ActiveWorkbook.Sheets("Main").Range("D28").Value = ""
    End If
End Sub
Private Sub ComboBox10_Change()
    If ComboBox10.Value <> "Select Type" Then
        ActiveWorkbook.Sheets("Main").Range("D29").Value = ComboBox10.Value
    Else
        ActiveWorkbook.Sheets("Main").Range("D29").Value = ""
    End If
End Sub




'-------------------------------------------------------------------------------Process

Private Sub CommandButton2_Click()
 Call Proce

End Sub



Private Sub Import_Click()
 
Dim ExistS As Boolean
 
 '------------------------------------- Create Worksheet
 
 MeterName = ActiveWorkbook.Sheets("Main").Range(ActiveCell.Address).Value
 StatAdd = ActiveCell.Offset(, 2).Address()
 
 If Intersect(ActiveCell, Range("C20:C35")) Is Nothing Then
    MsgBox "Select the Meter Name to proceed. Try Again."
    Exit Sub
 Else
    If ActiveCell.Offset(, 1).Value = "" Then
       MsgBox "Select Meter Type first! Try Again"
       Exit Sub
    End If
 End If
 
 For Each sht In ThisWorkbook.Worksheets 'Check if the worksheet is already existing
    If sht.Name = MeterName Then
        ExistS = True
        Exit For
    End If
 Next sht
 
 If ExistS = False Then 'Create if not existing
    Sheets.Add(After:=Sheets(Sheets.Count)).Name = MeterName
 End If

 ActiveWorkbook.Sheets("Main").Activate

 '-------------------------------------- Calling Importing Procedures
 
 PQq = False
 
 Call ImpoW
 If Cont = False Then
    Exit Sub
 End If
 Call WPaster
 
 '---------------------------------- PQ Continuation
 
 If PQq = True Then
    Call PPaster
    PQq = False
    Cont = False
    Exit Sub
 End If
 
 '-----------------------------------PQ Logs Normal Sequence
 Call ImpoP
 If Cont = False Then
    Exit Sub
 End If
 Call PPaster
 
 
 PQq = False
 Cont = False
End Sub

Private Sub Import2_Click()
 Call CImpo
 If CCont = False Then
    MsgBox "No content"
    Exit Sub
 End If
 Call CPaster
 Cont = False
End Sub


Private Sub Clearbut_Click()
 Call Clears
End Sub

 Private Sub Deletes_Click()
 Call Clears
 For Each shts In ThisWorkbook.Worksheets 'Check if the worksheet is already existing
    If shts.Name = ActiveCell.Value Then
        Sheets(ActiveCell.Value).Delete
        Exit For
    End If
 Next shts
 ActiveCell.Value = "Meter " & ActiveCell.Row - 19
 End Sub

